print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/chuck/Desktop/DT FALL 2016/BUILDING WORLD/pot-of-mussels/mussels/Assets/mussel_shell_left_smoothed.ma"`)
{		
	file -o "/Users/chuck/Desktop/DT FALL 2016/BUILDING WORLD/pot-of-mussels/mussels/Assets/mussel_shell_left_smoothed.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/chuck/Desktop/DT FALL 2016/BUILDING WORLD/pot-of-mussels/mussels/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/chuck/Desktop/DT FALL 2016/BUILDING WORLD/pot-of-mussels/mussels/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/chuck/Desktop/DT FALL 2016/BUILDING WORLD/pot-of-mussels/mussels/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
